import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { buildToc, updateToc } from '../src/toc.js'

const fixture = (name) => readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf8')

const START = '<!-- START foldtoc -->'
const NOTICE = '<!-- Generated by foldtoc. Do not edit this section; re-run foldtoc to update it. -->'
const END = '<!-- END foldtoc -->'

test('renders the reference example exactly', () => {
  assert.equal(buildToc(fixture('example-doc.md')), fixture('example-toc.md').trimEnd())
})

test('flat headings become a plain list', () => {
  assert.equal(buildToc('# A\n\n# B\n'), '**Table of Contents**\n\n- [A](#a)\n- [B](#b)')
})

test('a lone top-level entry starts expanded so the TOC is not hidden', () => {
  assert.equal(
    buildToc('# Project\n\n## Install\n\n## Usage\n'),
    [
      '**Table of Contents**',
      '',
      '- <details open><summary><a href="#project">Project</a></summary>',
      '',
      '  - [Install](#install)',
      '  - [Usage](#usage)',
      '  </details>',
    ].join('\n'),
  )
})

test('skipped heading levels still nest under the nearest shallower heading', () => {
  assert.equal(
    buildToc('# A\n\n### Deep\n\n# B\n', { title: '' }),
    [
      '- <details><summary><a href="#a">A</a></summary>',
      '',
      '  - [Deep](#deep)',
      '  </details>',
      '',
      '- [B](#b)',
    ].join('\n'),
  )
})

test('inline markdown is kept in links and converted to HTML inside <summary>', () => {
  const toc = buildToc('# `Vec<T>` and **bold**\n\n## See [docs](https://x.y) & [a] b\n\n# Z\n', { title: '' })
  assert.equal(
    toc,
    [
      '- <details><summary><a href="#vect-and-bold"><code>Vec&lt;T&gt;</code> and <strong>bold</strong></a></summary>',
      '',
      '  - [See docs & \\[a\\] b](#see-docs--a-b)',
      '  </details>',
      '',
      '- [Z](#z)',
    ].join('\n'),
  )
})

test('multi-line setext headings stay on one TOC line', () => {
  // GitHub drops the newline when building the anchor, so the words run together there.
  assert.equal(buildToc('Two\nlines\n=====\n', { title: '' }), '- [Two lines](#twolines)')
})

test('custom title, no title and entry prefix', () => {
  assert.equal(buildToc('# A\n', { title: '## Contents' }), '## Contents\n\n- [A](#a)')
  assert.equal(buildToc('# A\n', { title: '' }), '- [A](#a)')
  assert.equal(buildToc('# A\n', { title: '', entryPrefix: '*' }), '* [A](#a)')
})

test('minLevel and maxLevel filter headings', () => {
  const doc = '# Title\n\n## A\n\n### A1\n\n## B\n'
  assert.equal(buildToc(doc, { title: '', minLevel: 2 }), [
    '- <details><summary><a href="#a">A</a></summary>',
    '',
    '  - [A1](#a1)',
    '  </details>',
    '',
    '- [B](#b)',
  ].join('\n'))
  assert.equal(buildToc(doc, { title: '', minLevel: 2, maxLevel: 2 }), '- [A](#a)\n- [B](#b)')
})

test('gitlab anchors', () => {
  assert.equal(buildToc('# Heap / Queue\n\n# Heap / Queue\n', { title: '', anchors: 'gitlab' }),
    '- [Heap / Queue](#heap-queue)\n- [Heap / Queue](#heap-queue-1)')
})

test('inserts the TOC at the top when there are no markers', () => {
  const result = updateToc('# A\n\ntext\n')
  assert.equal(result.status, 'updated')
  assert.equal(result.content, `${START}\n${NOTICE}\n**Table of Contents**\n\n- [A](#a)\n\n${END}\n\n# A\n\ntext\n`)
})

test('running twice changes nothing', () => {
  const once = updateToc(fixture('example-doc.md')).content
  const twice = updateToc(once)
  assert.equal(twice.status, 'unchanged')
  assert.equal(twice.content, once)
})

test('replaces an existing doctoc TOC in place', () => {
  const doc = [
    '# Title',
    '',
    '<!-- START doctoc generated TOC please keep comment here to allow auto update -->',
    "<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->",
    '- [old](#old)',
    '',
    '<!-- END doctoc generated TOC please keep comment here to allow auto update -->',
    '',
    '## One',
    '',
  ].join('\n')
  assert.equal(
    updateToc(doc).content,
    `# Title\n\n${START}\n${NOTICE}\n**Table of Contents**\n\n- [One](#one)\n\n${END}\n\n## One\n`,
  )
})

test('headings above the TOC are left out unless all is set', () => {
  const doc = `# Title\n\n${START}\n${END}\n\n## One\n`
  assert.match(updateToc(doc).content, /- \[One\]\(#one\)\n/)
  assert.doesNotMatch(updateToc(doc).content, /\(#title\)/)
  assert.match(updateToc(doc, { all: true }).content, /<a href="#title">Title<\/a>/)
})

test('ignores markers and headings inside code blocks', () => {
  const doc = `# Real\n\n\`\`\`md\n${START}\n# Fake\n${END}\n\`\`\`\n`
  const { content } = updateToc(doc)
  assert.ok(content.startsWith(`${START}\n${NOTICE}\n**Table of Contents**\n\n- [Real](#real)\n\n${END}\n\n# Real`))
  assert.doesNotMatch(content, /#fake/)
})

test('puts the TOC after front matter and does not read front matter as headings', () => {
  const doc = '---\ntitle: Hello\n---\n# A\n'
  assert.equal(updateToc(doc).content, `---\ntitle: Hello\n---\n\n${START}\n${NOTICE}\n**Table of Contents**\n\n- [A](#a)\n\n${END}\n\n# A\n`)
})

test('a SKIP comment leaves the file alone', () => {
  for (const tag of ['<!-- DOCTOC SKIP -->', '<!-- FOLDTOC SKIP -->']) {
    const doc = `${tag}\n\n# A\n`
    assert.deepEqual(updateToc(doc), { content: doc, status: 'skipped', reason: 'skip comment' })
  }
})

test('an EXCLUDE comment drops that heading and its sub-sections', () => {
  const doc = '# A\n\n<!-- FOLDTOC EXCLUDE -->\n# Changelog\n\n## v1\n\n# B\n\n<!-- DOCTOC EXCLUDE -->\n## B1\n'
  assert.equal(buildToc(doc, { title: '' }), '- [A](#a)\n- [B](#b)')
})

test('updateOnly skips files without a TOC', () => {
  assert.deepEqual(updateToc('# A\n', { updateOnly: true }), { content: '# A\n', status: 'skipped', reason: 'no existing TOC' })
})

test('files without headings are skipped', () => {
  assert.deepEqual(updateToc('just text\n'), { content: 'just text\n', status: 'skipped', reason: 'no headings' })
})

test('keeps Windows line endings', () => {
  const { content } = updateToc('# A\r\n\r\ntext\r\n')
  assert.equal(content, `${START}\r\n${NOTICE}\r\n**Table of Contents**\r\n\r\n- [A](#a)\r\n\r\n${END}\r\n\r\n# A\r\n\r\ntext\r\n`)
})

test('a START marker without END is an error', () => {
  assert.throws(() => updateToc(`${START}\n\n# A\n`), /START marker without a matching END marker/)
})
