import { parseDocument } from './markdown.js'
import { renderToc } from './render.js'
import { createSlugger } from './slug.js'

const START = '<!-- START foldtoc -->'
const NOTICE = '<!-- Generated by foldtoc. Do not edit this section; re-run foldtoc to update it. -->'
const END = '<!-- END foldtoc -->'

/**
 * @typedef {object} TocOptions
 * @property {'github' | 'gitlab'} [anchors] anchor style (default 'github')
 * @property {string} [title] markdown above the list; '' for none
 * @property {number} [minLevel] shallowest heading level to include (default 1)
 * @property {number} [maxLevel] deepest heading level to include (default 6)
 * @property {boolean} [all] also include headings above the TOC
 * @property {boolean} [updateOnly] leave files without a TOC alone
 * @property {'-' | '*' | '+'} [entryPrefix] list bullet (default '-')
 */

/** Returns the TOC for `content` (title and list, without markers). */
export function buildToc(content, options = {}) {
  return renderToc(selectEntries(parseDocument(content), options), options)
}

/**
 * Inserts or refreshes the TOC in `content`.
 *
 * @param {string} content
 * @param {TocOptions} [options]
 * @returns {{content: string, status: 'updated' | 'unchanged' | 'skipped', reason?: string}}
 */
export function updateToc(content, options = {}) {
  const doc = parseDocument(content)
  if (doc.skip) return skipped(content, 'skip comment')
  if (!doc.toc && options.updateOnly) return skipped(content, 'no existing TOC')
  const entries = selectEntries(doc, options)
  if (!entries.length && !doc.toc) return skipped(content, 'no headings')

  const eol = content.includes('\r\n') ? '\r\n' : '\n'
  const list = renderToc(entries, options)
  const block = [START, NOTICE, ...(list ? [list, ''] : []), END].join('\n').replace(/\n/g, eol)

  let next
  if (doc.toc) {
    next = content.slice(0, doc.toc.start) + block + content.slice(doc.toc.end)
  } else {
    // No markers yet: put the TOC at the top, below any front matter.
    const before = content.slice(0, doc.bodyStart)
    const after = content.slice(doc.bodyStart).replace(/^(?:[ \t]*\r?\n)+/, '')
    const gap = before.trim() ? (before.endsWith('\n') ? eol : eol + eol) : ''
    next = before + gap + block + eol + eol + after
  }
  return { content: next, status: next === content ? 'unchanged' : 'updated' }
}

/**
 * The anchor the host gives each of `doc.headings`, or null for headings inside
 * the existing TOC (which is about to be replaced).
 */
export function anchorHeadings(doc, anchors) {
  const slug = createSlugger(anchors)
  const tocStart = doc.toc?.start ?? doc.bodyStart
  const tocEnd = doc.toc?.end ?? doc.bodyStart
  // Every heading outside the TOC gets an anchor on the host, even ones the
  // TOC leaves out, so all of them are slugged to keep "-1", "-2" in step.
  return doc.headings.map((heading) =>
    heading.start >= tocStart && heading.start < tocEnd ? null : slug(heading.text),
  )
}

function selectEntries(doc, { anchors, minLevel = 1, maxLevel = 6, all = false }) {
  const anchorList = anchorHeadings(doc, anchors)
  const tocStart = doc.toc?.start ?? doc.bodyStart
  const entries = []
  let excludedLevel = Infinity // level of the EXCLUDEd section we are inside, if any

  for (const [index, heading] of doc.headings.entries()) {
    const anchor = anchorList[index]
    if (anchor === null || heading.nested) continue

    if (heading.level <= excludedLevel) excludedLevel = Infinity
    if (heading.excluded) excludedLevel = heading.level
    if (excludedLevel !== Infinity) continue

    if (!all && heading.start < tocStart) continue
    if (heading.level < minLevel || heading.level > maxLevel || !heading.markdown) continue
    entries.push({ level: heading.level, anchor, markdown: heading.markdown, html: heading.html })
  }
  return entries
}

const skipped = (content, reason) => ({ content, status: 'skipped', reason })
